блок Comment
KushnirUO/superhero-shop pull request #1
Opened 2022-05-18 15:16 UTC by AndreyDash

2022-05-18 19:26 UTC, KushnirUO commented on tech/tech.html
> +
Ваш блок має лежати в блоці "techBlock"

2022-05-18 19:29 UTC, KushnirUO commented on tech/tech.html
> +            <!-- <img src="Star.png" />
Видаліть коментарі з фінальної версії коду

2022-05-18 19:32 UTC, KushnirUO requested changes
Назвіть гілку так, як вказано в завданні, та подивіться правки в коді

2022-05-18 20:11 UTC, AndreyDash commented on tech/tech.html
> +
в завданні блок має називатися "user-comment", я так назвав верхній та нижній підблоки, а це має бути назва всього блоку з двох частин всередині верхньої та нижньої, правильно?

2022-05-18 20:18 UTC, KushnirUO commented on tech/tech.html
> +
Так, це має бути назва всього блоку і така ж сама назва гілки в github

2022-05-18 20:18 UTC, AndreyDash commented on tech/tech.html
> +
тобто це має виглядати так:
<div class="techBlock">
      <div class="user-comment">

2022-05-18 20:23 UTC, AndreyDash commented on tech/tech.html
> +
<div class="techBlock">
      <div class="user-comment">

2022-05-18 20:25 UTC, AndreyDash commented on tech/tech.html
> +
....<div class="techBlock">
      <div class="user-comment">....

2022-05-18 20:26 UTC, KushnirUO commented on tech/tech.html
> +
так

2022-05-19 07:05 UTC, closed without merging

2022-05-19 08:02 UTC, AndreyDash commented on tech/tech.html
> +
я перейминував гілку, видалив стару гілку, та спробував запушити на GitHub нову гілку,
але пише:
error: remote upstream already exists.

2022-05-19 08:20 UTC, KushnirUO commented on tech/tech.html
> +
Спробуйте створити новий пул реквест

2022-05-19 08:27 UTC, AndreyDash commented on tech/tech.html
> +
я видалив стару гілку з вашого репозитарію
зараз немає ніякої моєї гілки взагалі на вашому репозіторії
нічого  немає для пул реквесту