form-checkbox
KushnirUO/superhero-shop pull request #8
Opened 2022-05-23 19:49 UTC by OleksandrZaiets

2022-05-24 09:38 UTC, KushnirUO requested changes
checkBox не відповідає дизайну, має бути сірий фон, та відсутність рамок, до його натискання

2022-05-24 09:38 UTC, KushnirUO commented on style.css
> +.galochka {
не називайте так класи, назвіть краще check-mark

2022-05-24 09:38 UTC, KushnirUO commented on style.css
> +label {
Ви присвоїли ці стилі усім лейблам на сторінці, але врахуйте, що не тільки у вас використовуються лейбли, тому змініть це

2022-05-26 10:53 UTC, OleksandrZaiets commented
Виправив, можете перевірити)

2022-05-27 09:49 UTC, merged